"""ContentSnack model for storing content generated by n8n shredder."""
from datetime import datetime, timezone
from typing import Optional
from uuid import UUID, uuid4

from sqlalchemy import String, DateTime, Text, ForeignKey, func, UUID as SQLAlchemyUUID
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class ContentSnack(Base):
    """Model for storing content snippets generated by n8n shredder."""
    
    __tablename__ = "content_snacks"
    
    # Primary key - UUID
    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        default=uuid4,
        server_default=func.uuid_generate_v4(),
    )
    
    # Foreign key to MarketingAsset
    asset_id: Mapped[UUID] = mapped_column(
        SQLAlchemyUUID,
        ForeignKey("marketing_assets.id"),
        nullable=False,
        index=True,
    )
    
    # Content type - enum-like field
    content_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )
    
    # Content text
    content_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    
    # Metadata JSONB (hashtags, target audience, etc.)
    metadata: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        default=None,
    )
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
    )
    
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime,
        nullable=True,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )
    
    # Relationship to MarketingAsset
    asset: Mapped["MarketingAsset"] = relationship(
        "MarketingAsset",
        back_populates="snacks",
        lazy="selectin",  # Async-compatible loading strategy
    )
    
    def __repr__(self) -> str:
        """String representation of the model."""
        return f"<ContentSnack(id={self.id}, asset_id={self.asset_id}, content_type={self.content_type})>"
