"""Router for email sequence generation endpoints."""
import logging
from uuid import UUID

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.status import ResponseStatus
from app.schemas.sequence import ClaudeOutreachView
from app.services.sequence_service import SequenceService
from app.services.generation_service import GenerationService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/sequence", tags=["sequence"])


@router.post(
    "/generate/{job_id}",
    status_code=status.HTTP_202_ACCEPTED,
    response_model=dict,
)
async def generate_sequence_endpoint(
    job_id: str,
    background_tasks: BackgroundTasks,
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Generate an 8-touch email sequence for a job.
    
    This endpoint uses FastAPI's BackgroundTasks to run the sequence generation
    asynchronously without blocking the HTTP response.
    
    Args:
        job_id: The enrichment job ID (UUID string).
        background_tasks: FastAPI background tasks manager.
        db: Async database session.
    
    Returns:
        dict: Response with job_id and sequence_id, status 202 Accepted.
    
    Raises:
        HTTPException: If the job_id is invalid or the job is not found.
    """
    try:
        # Validate job_id format
        uuid_job_id = UUID(job_id)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid job ID format: {job_id}",
        )
    
    # Initialize service
    service = SequenceService(db)
    
    # Get or create sequence using service
    sequence = await service.get_or_create_sequence(uuid_job_id)
    
    # Add the generation task to background tasks
    # The task will run asynchronously without blocking the HTTP response
    # Note: GenerationService.generate_sequence creates its own DB session internally
    # to avoid using the request-scoped session that gets closed after response
    generation_service = GenerationService()
    background_tasks.add_task(
        generation_service.generate_sequence,
        job_id=job_id,
    )
    
    logger.info(f"Sequence generation initiated for job {job_id}")
    
    # Return immediately with 202 Accepted
    return {
        "job_id": job_id,
        "sequence_id": str(sequence.id),
        "status": ResponseStatus.ACCEPTED,
        "message": "Sequence generation started in background",
    }


@router.get(
    "/job/{job_id}",
    response_model=ClaudeOutreachView,
    status_code=status.HTTP_200_OK,
    summary="Get sequence data for a job",
    description="Retrieve the validated sequence data generated for a job.",
)
async def get_sequence_endpoint(
    job_id: str,
    db: AsyncSession = Depends(get_db)
) -> ClaudeOutreachView:
    """Get the validated sequence data for a job.
    
    This endpoint returns the transformed, validated sequence data that was
    generated by Claude and stored in the database.
    
    Args:
        job_id: The job identifier (UUID string).
        db: Async database session.
    
    Returns:
        ClaudeOutreachView: Validated sequence data with touches and strategy.
    
    Raises:
        HTTPException: If job or sequence is not found, or data not yet generated.
    """
    try:
        # Initialize service
        service = SequenceService(db)
        
        # Get sequence data using service
        return await service.get_sequence_data(job_id)
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch sequence data: {str(e)}",
        )
